### ISSUE TITLE
[macOS] just to confirm it works!

### ISSUE THREAD

**Issue by kozyilmaz** [adityapk00/zec-qt-wallet#12]
Tried with my macOS builds of `zcashd` v2.0.1 (https://github.com/kozyilmaz/zcash-apple/releases) and Qt 5.11.1. Confirm it works, great job!

```
$ /Users/loki/Qt5.11.1/5.11.1/clang_64/bin/qmake -v
QMake version 3.1
Using Qt version 5.11.1 in /Users/loki/Qt5.11.1/5.11.1/clang_64/lib
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
$ clang -v
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Found CUDA installation: /usr/local/cuda, version unknown
```

**Comment by adityapk00** [comment]
Awesome! Thanks a ton. 

I currently don't have access to a Mac, so I haven't been able to test it. Thanks for trying it out. 

Was it also able to auto-discover zcashd and connect to it? The code [here](https://github.com/adityapk00/zcash-qt-wallet/blob/fed17ba0ee235cf12fb85fe720e2c0a35ee4ade2/src/settings.cpp#L102) tries to auto-detect zcashd. Did it work correctly for your builds of zcashd?

Thanks for trying it out.

**Comment by garethtdavies** [comment]
Also managed to build this on a Mac and works nicely 👍 

No, it doesn't get the config file correctly (I set the config manually). On macOS it's in `~/Library/Application Support/Zcash/zcash.conf`

**Comment by kozyilmaz** [comment]
Yes, sent a PR https://github.com/adityapk00/zec-qt-wallet/pull/15

**Comment by adityapk00** [comment]
Thanks @kozyilmaz. Merged!
