### ISSUE TITLE
Compiling on Debian Stretch

### ISSUE THREAD

**Issue by dreadlokeur** [adityapk00/zec-qt-wallet#16]
Hey,

I have an error when i try compiling on debian : 

"src/balancestablemodel.cpp: In member function ‘void BalancesTableModel::setNewData(const QMap<QString, double>*, const QList<UnspentOutput>*)’:
src/balancestablemodel.cpp:23:26: error: ‘const class QMap<QString, double>’ has no member named ‘constKeyValueBegin’; did you mean ‘constBegin’?
  std::for_each(balances->constKeyValueBegin(), balances->constKeyValueEnd(), [=] (auto it) {
                          ^~~~~~~~~~~~~~~~~~
src/balancestablemodel.cpp:23:58: error: ‘const class QMap<QString, double>’ has no member named ‘constKeyValueEnd’; did you mean ‘constEnd’?
  std::for_each(balances->constKeyValueBegin(), balances->constKeyValueEnd(), [=] (auto it) {
"

**Comment by adityapk00** [comment]
Thanks for reporting this. I briefly looked into it, and I suspect your version of Qt is < 5.10. What's the output of `qmake -version`? 

Can you try installing the latest version (5.11.2) of Qt?

I'll spend some time early next week trying to get it to compile with lower versions of Qt.. Thanks!

**Comment by adityapk00** [comment]
Can you git pull and try again? I think I might have fixed it with commit: d3c4b42a160cb309f4d14d962960801e96835c75

**Comment by dreadlokeur** [comment]
QMake version 3.0                                                                                                                                                                                                                                                              
Using Qt version 5.7.1 in /usr/lib/x86_64-linux-gnu

I have pull your last commit, and now i have : 

src/senttxstore.cpp: In static member function ‘static void SentTxStore::addToSentTx(Tx, QString)’:
src/senttxstore.cpp:90:39: error: ‘class QDateTime’ has no member named ‘currentSecsSinceEpoch’; did you mean ‘currentMSecsSinceEpoch’?
     txItem["datetime"]  = QDateTime().currentSecsSinceEpoch();
                                       ^~~~~~~~~~~~~~~~~~~~~
g++ -c -include bin/zec-qt-wallet -m64 -pipe -g -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DAPP_VERSION=\"0.2.4\" -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc/3rdparty -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibin -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o bin/txtablemodel.o src/txtablemodel.cpp                                                                                                                                                                                                                                                
g++ -c -include bin/zec-qt-wallet -m64 -pipe -g -std=gnu++1y -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DAPP_VERSION=\"0.2.4\" -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc/3rdparty -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibin -Isrc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o bin/utils.o src/utils.cpp                                                                                                                                                                                                                                                              
src/txtablemodel.cpp: In member function ‘virtual QVariant TxTableModel::data(const QModelIndex&, int) const’:
src/txtablemodel.cpp:101:24: error: ‘fromSecsSinceEpoch’ is not a member of ‘QDateTime’
         case 2: return QDateTime::fromSecsSinceEpoch(modeldata->at(index.row()).datetime).toLocalTime().toString();
                        ^~~~~~~~~
src/txtablemodel.cpp:117:24: error: ‘fromSecsSinceEpoch’ is not a member of ‘QDateTime’
         case 2: return QDateTime::fromSecsSinceEpoch(modeldata->at(index.row()).datetime).toLocalTime().toString();

**Comment by dreadlokeur** [comment]
diff --git a/src/senttxstore.cpp b/src/senttxstore.cpp
index 656fe05..8c9c7f5 100644
--- a/src/senttxstore.cpp
+++ b/src/senttxstore.cpp
@@ -87,7 +87,7 @@
     QJsonObject txItem;
     txItem["type"]      = "sent";
     txItem["from"]      = tx.fromAddr;
-    txItem["datetime"]  = QDateTime().currentSecsSinceEpoch();
+    txItem["datetime"]  = QDateTime().currentMSecsSinceEpoch();
     txItem["address"]   = QString();    // The sent address is blank, to be consistent with t-Addr sent behaviour
     txItem["txid"]      = txid;
     txItem["amount"]    = -totalAmount;
diff --git a/src/txtablemodel.cpp b/src/txtablemodel.cpp
index d3834a1..96fbe3b 100644
--- a/src/txtablemodel.cpp
+++ b/src/txtablemodel.cpp
@@ -98,7 +98,7 @@
                     else 
                         return addr;
                 }
-        case 2: return QDateTime::fromSecsSinceEpoch(modeldata->at(index.row()).datetime).toLocalTime().toString();
+        case 2: return QDateTime::fromMSecsSinceEpoch(modeldata->at(index.row()).datetime).toLocalTime().toString();
         case 3: return Settings::getInstance()->getZECDisplayFormat(modeldata->at(index.row()).amount);
         }
     } 
@@ -114,7 +114,7 @@
                     else 
                         return addr;
                 }
-        case 2: return QDateTime::fromSecsSinceEpoch(modeldata->at(index.row()).datetime).toLocalTime().toString();
+        case 2: return QDateTime::fromMSecsSinceEpoch(modeldata->at(index.row()).datetime).toLocalTime().toString();
         case 3: return Settings::getInstance()->getUSDFormat(modeldata->at(index.row()).amount);
         }    
     }

**Comment by adityapk00** [comment]
Ah, thanks for the detailed feedback. I’ll this

**Comment by adityapk00** [comment]
Oh, you already sent a PR! Thanks! 

Merged.
