### ISSUE TITLE
Feature request: Labeling and address book

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zec-qt-wallet#23]
Please implement labeling and address book for addresses.

See https://github.com/ZECmate/ZECmate-swing-wallet for implementation ideas.

**Comment by rex4539** [comment]
Verified as fixed.

**Comment by adityapk00** [comment]
Actually, lets leave this one open until we add labeling for your own addresses and autocomplete etc...

**Comment by adityapk00** [comment]
Auto complete: commit b60d65ee822c8cb463621c0a826cc19c91f3099e

**Comment by adityapk00** [comment]
Fixed in v0.2.9
