### ISSUE TITLE
Compilation fails after latest merge

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zec-qt-wallet#33]
```
src/connection.cpp:407:10: error: use of undeclared identifier 'paramsLocation'
    if (!paramsLocation.exists()) {
         ^
src/connection.cpp:408:23: error: use of undeclared identifier 'paramsLocation'
        QDir().mkpath(paramsLocation.absolutePath());
                      ^
src/connection.cpp:411:12: error: use of undeclared identifier 'paramsLocation'
    return paramsLocation.absolutePath();
           ^
```

It was introduced here -> https://github.com/adityapk00/zec-qt-wallet/commit/3cbb1cac3d943e85633df55199a49ed87e75852d#diff-a2a82fe964a7b85f20cd5239d386184aR236

**Comment by rex4539** [comment]
After latest pull it fails with

```
src/connection.cpp:406:25: error: no member named 'exists' in 'QString'
    if (!paramsLocation.exists()) {
         ~~~~~~~~~~~~~~ ^
src/connection.cpp:407:38: error: no member named 'absolutePath' in 'QString'
        QDir().mkpath(paramsLocation.absolutePath());
                      ~~~~~~~~~~~~~~ ^
src/connection.cpp:410:27: error: no member named 'absolutePath' in 'QString'
    return paramsLocation.absolutePath();
           ~~~~~~~~~~~~~~ ^
```

**Comment by adityapk00** [comment]
I'm terribly sorry :) I think I really fixed it this time. 

I just ordered a Mac, so I should be able to run tests on a Mac myself rather than do it blindly starting next week :)

**Comment by rex4539** [comment]
Fixed :)

**Comment by adityapk00** [comment]
Also, on a Mac, do you know what the location of the params directory is? On Linux its ~/.zcash-params. Is it same on Mac?

**Comment by rex4539** [comment]
https://github.com/zcash/zcash/blob/0f091f228cdb1793a10ea59f82b7c7f0b93edb7a/src/util.cpp#L500

**Comment by adityapk00** [comment]
Thank you! Fixed. 

Just FYI: I just added support for an embedded zcashd. Mac is not supported yet, so you might see funny error messages if an external zcashd is not running when starting zec-qt-wallet.
