### ISSUE TITLE
Do not display address in Send validation error window

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zec-qt-wallet#37]
Reproducibility: always

Steps:
1. Send -> Address -> Enter a ridiculously long string
2. Click on "Send" button.

What happened:
![screen shot 2018-11-10 at 11 32 15](https://user-images.githubusercontent.com/227442/48299903-a6f7dd00-e4dc-11e8-8160-434e541a8eb6.png)

Expected result:
The error message is a generic "Recipient Address is Invalid", without displaying the actual string.

**Comment by rex4539** [comment]
No change after the above commit. I get the exact same issue.

**Comment by adityapk00** [comment]
Really? I'm truncating after 100 chars, because a Sprout address can be upto 94 chars. Also, I think we should display the address that is invalid in the window, because you might have multiple send addresses in the send window, and we should identify the one that is invalid.

**Comment by rex4539** [comment]
It actually displays 101 in the error window but ok :)

**Comment by rex4539** [comment]
How do you separate each address? I tried a valid and then an invalid address but both were shown in the error window. I would expect only the invalid one to be shown. I tried both with whitespace and comma.

**Comment by rex4539** [comment]
Also, trying to add another address from the Address Book, replaces the previous one.

**Comment by adityapk00** [comment]
Oh, there's an "Add Address button on the send tab page. Maybe it is not obvious enough?

![image](https://user-images.githubusercontent.com/31996805/48304801-c25eea00-e4d4-11e8-8dd7-370df2f3269a.png)

**Comment by rex4539** [comment]
Ha, somehow I thought this button allowed to add a new address that you typed in the Address field :)]

Perhaps rename the button to "Add Another Recipient"?

**Comment by rex4539** [comment]
Thanks!
