### ISSUE TITLE
Custom Fee

### ISSUE THREAD

**Issue by PRabahy** [adityapk00/zec-qt-wallet#48]
It would be nice if there was a way to set a custom fee. Using WinZEC, I was able to manually set a fee all the way down to 0. Right now the zcash network isn't really full, so the fee doesn't actually do much.

**Comment by adityapk00** [comment]
Commit: 448b2ceca8345d29ccc39cbcab3af799f73e8d15

**Comment by adityapk00** [comment]
In v0.3.1

**Comment by garethtdavies** [comment]
The default fee is there for a very good reason. All fees are transparent so using a custom fee makes all transactions indistinguishable. If you are solely using t-addrs then fair enough this is a moot point as everything is visible. I'd expect users of zec-qt-wallet to shielded tx users and in which case using the default fee is highly recommended. I'm not against setting a custom fee for those who know what they are doing but suggest flagging a warning if anyone changes the fee.

**Comment by adityapk00** [comment]
Yup, got this feedback from elsewhere as well. I will add a warning on the confirm page.
